"use client";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import {
  Zap,
  Cpu,
  Brain,
  Mic,
  Eye,
  Target,
  Activity,
  Layers,
  Cloud,
  Monitor,
  ExternalLink,
  FileText,
  ChevronRight,
  Github,
  Globe,
  Gauge,
  Timer,
  TrendingUp,
  Users,
  Trophy,
  Sparkles,
} from "lucide-react";

const INFRASTRUCTURE = [
  {
    icon: Monitor,
    title: "NVIDIA DGX Spark",
    subtitle: "Edge AI — GB10 Superchip",
    description: "17-keypoint real-time pose estimation at 15+ FPS with <50ms latency. YOLOv8n-pose runs directly on the GB10 Superchip for instant skeleton extraction.",
    color: "text-green-400",
    bg: "bg-green-400/10",
    border: "border-green-400/20",
    stats: ["15+ FPS", "<50ms", "17 keypoints"],
  },
  {
    icon: Cloud,
    title: "Modal + NVIDIA A100",
    subtitle: "Cloud GPU — HY-Motion 1.0-Lite",
    description: "Tencent's SOTA text-to-3D motion model (Dec 2025, 0.46B params) deployed on A100 GPU. Generates 30-frame motion sequences from text in ~26 seconds.",
    color: "text-purple-400",
    bg: "bg-purple-400/10",
    border: "border-purple-400/20",
    stats: ["0.46B params", "~26s gen", "A100 80GB"],
  },
  {
    icon: Brain,
    title: "Anthropic Claude Agent SDK",
    subtitle: "Multi-Agent Orchestration",
    description: "Claude Sonnet 4 orchestrates 44 MCP tools across 12 categories. 3 sub-agents (Perception, Coach, Communicator) with hooks for safety and audit.",
    color: "text-orange-400",
    bg: "bg-orange-400/10",
    border: "border-orange-400/20",
    stats: ["44 tools", "3 agents", "12 categories"],
  },
  {
    icon: Mic,
    title: "OpenAI Realtime API",
    subtitle: "Bidirectional Voice Coaching",
    description: "GPT-4o Realtime API delivers natural voice coaching with 3-layer interruption handling. Context injection feeds live pose scores into voice.",
    color: "text-blue-400",
    bg: "bg-blue-400/10",
    border: "border-blue-400/20",
    stats: ["3-layer interruption", "GPT-4o", "Real-time"],
  },
  {
    icon: Eye,
    title: "Computer Vision Pipeline",
    subtitle: "MediaPipe + YOLOv8n-pose",
    description: "33 body landmarks + 21 hand landmarks tracked in real-time. Phase detection identifies preparation → execution → peak → recovery automatically.",
    color: "text-cyan-400",
    bg: "bg-cyan-400/10",
    border: "border-cyan-400/20",
    stats: ["33+21 landmarks", "4 phases", "30 FPS"],
  },
  {
    icon: Target,
    title: "Triple-Metric Scoring",
    subtitle: "Gaussian + Cosine + COCO OKS",
    description: "Three complementary metrics for robust pose evaluation: Gaussian joint angles (σ=15°), Cosine spatial similarity, and COCO OKS — the academic standard.",
    color: "text-rose-400",
    bg: "bg-rose-400/10",
    border: "border-rose-400/20",
    stats: ["3 metrics", "16 angles", "σ=15°"],
  },
];

const EXPERT_TIERS = [
  { tier: "1", name: "Canonical Templates", latency: "Instant", desc: "10+ pre-built exercises with biomechanically accurate joint angles per phase" },
  { tier: "2", name: "Claude Semantic Mapping", latency: "~0.5s", desc: "Natural language → canonical exercise mapping via Claude" },
  { tier: "3", name: "Claude Angle Generation", latency: "~1s", desc: "Novel skill description → per-phase joint angles generated by Claude" },
  { tier: "4", name: "HY-Motion on Modal A100", latency: "~26s", desc: "SOTA text-to-3D motion diffusion generates full skeleton sequences" },
];

const MODELS = [
  "YOLOv8n-pose", "MediaPipe Pose", "MediaPipe Hands", "HY-Motion 1.0-Lite",
  "CLIP-ViT-Large", "Qwen3-8B", "Claude Sonnet 4", "GPT-4o Realtime",
  "OpenAI TTS", "OpenAI Whisper",
];

export default function ProductPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Hero */}
      <section className="relative overflow-hidden border-b border-border">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-purple-500/5" />
        <div className="relative mx-auto max-w-6xl px-6 py-16">
          <div className="flex items-center gap-3 mb-4">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary text-primary-foreground">
              <Zap className="h-6 w-6" />
            </div>
            <div>
              <h1 className="text-4xl font-bold tracking-tight">Kinetic AI</h1>
              <p className="text-muted-foreground">Real-Time AI Skill Coach with Expert Motion Transfer</p>
            </div>
          </div>

          <p className="mt-6 max-w-2xl text-lg text-muted-foreground">
            Learn any physical skill from any expert — in real-time, through voice.
            No expert video needed. Just describe the skill and Kinetic generates
            the reference using state-of-the-art 3D motion generation.
          </p>

          <div className="mt-8 flex flex-wrap gap-3">
            <a
              href="https://github.com/rajashekarcs2023/treehacks2026-kinetic"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 rounded-lg bg-foreground px-4 py-2.5 text-sm font-medium text-background transition hover:bg-foreground/90"
            >
              <Github className="h-4 w-4" /> GitHub Repository
            </a>
            <a
              href="https://rajashekarvennavelli--aegis-motion-generate-endpoint.modal.run"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2.5 text-sm font-medium transition hover:bg-accent"
            >
              <Globe className="h-4 w-4" /> Modal API Endpoint
            </a>
            <a
              href="#research"
              className="inline-flex items-center gap-2 rounded-lg border border-primary/30 bg-primary/5 px-4 py-2.5 text-sm font-medium text-primary transition hover:bg-primary/10"
            >
              <FileText className="h-4 w-4" /> Technical Paper
            </a>
          </div>

          {/* Quick stats */}
          <div className="mt-10 grid grid-cols-2 sm:grid-cols-4 gap-4">
            {[
              { icon: Layers, value: "17,000+", label: "Lines of Code" },
              { icon: Cpu, value: "10", label: "AI Models" },
              { icon: Activity, value: "6", label: "Infrastructure Pillars" },
              { icon: Timer, value: "20hrs", label: "Solo-Built" },
            ].map((stat) => (
              <div key={stat.label} className="rounded-lg border border-border bg-card p-4">
                <stat.icon className="h-4 w-4 text-muted-foreground mb-2" />
                <div className="text-2xl font-bold">{stat.value}</div>
                <div className="text-xs text-muted-foreground">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Demo Video Placeholder */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-6xl px-6 py-12">
          <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary" /> Demo Video
          </h2>
          <div className="aspect-video rounded-xl border border-border bg-card flex items-center justify-center">
            <div className="text-center text-muted-foreground">
              <Activity className="h-12 w-12 mx-auto mb-3 opacity-50" />
              <p className="text-lg font-medium">Demo Video</p>
              <p className="text-sm">Loom recording coming soon</p>
            </div>
          </div>
        </div>
      </section>

      {/* Infrastructure Pillars */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-6xl px-6 py-12">
          <h2 className="text-2xl font-bold mb-2">6 Infrastructure Pillars</h2>
          <p className="text-muted-foreground mb-8">Each pillar represents a major technology powering the real-time coaching pipeline.</p>

          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {INFRASTRUCTURE.map((item) => (
              <Card key={item.title} className={`border ${item.border} bg-card transition hover:shadow-lg`}>
                <CardContent className="p-5">
                  <div className="flex items-center gap-3 mb-3">
                    <div className={`flex h-10 w-10 items-center justify-center rounded-lg ${item.bg}`}>
                      <item.icon className={`h-5 w-5 ${item.color}`} />
                    </div>
                    <div>
                      <h3 className="font-semibold text-sm">{item.title}</h3>
                      <p className="text-xs text-muted-foreground">{item.subtitle}</p>
                    </div>
                  </div>
                  <p className="text-sm text-muted-foreground mb-3">{item.description}</p>
                  <div className="flex flex-wrap gap-1.5">
                    {item.stats.map((stat) => (
                      <Badge key={stat} variant="secondary" className="text-xs">{stat}</Badge>
                    ))}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* AI Expert Generation Pipeline */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-6xl px-6 py-12">
          <h2 className="text-2xl font-bold mb-2">4-Tier AI Expert Generation</h2>
          <p className="text-muted-foreground mb-8">No expert video needed. Kinetic generates references through 4 tiers of increasing sophistication.</p>

          <div className="space-y-3">
            {EXPERT_TIERS.map((tier, i) => (
              <div key={tier.tier} className="flex items-start gap-4 rounded-lg border border-border bg-card p-4 transition hover:bg-accent/50">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary font-bold">
                  {tier.tier}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <h3 className="font-semibold">{tier.name}</h3>
                    <Badge variant="outline" className="text-xs">{tier.latency}</Badge>
                  </div>
                  <p className="text-sm text-muted-foreground">{tier.desc}</p>
                </div>
                {i < EXPERT_TIERS.length - 1 && (
                  <ChevronRight className="h-5 w-5 text-muted-foreground/30 mt-2.5 hidden sm:block" />
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-6xl px-6 py-12">
          <h2 className="text-2xl font-bold mb-6">How It Works</h2>
          <div className="rounded-xl border border-border bg-card p-6 font-mono text-sm leading-relaxed">
            <div className="text-muted-foreground">
              <span className="text-foreground font-medium">You say:</span> &quot;teach me a roundhouse kick&quot;<br /><br />
              <span className="text-primary">→ Tier 1:</span> Alias lookup... miss<br />
              <span className="text-primary">→ Tier 2:</span> Claude semantic mapping... no canonical match<br />
              <span className="text-primary">→ Tier 3:</span> Claude generates 4-phase joint angles (1.2s)<br />
              <span className="text-green-400">✓ Expert reference loaded</span> (16 joints × 4 phases)<br /><br />
              <span className="text-primary">→ Camera:</span> MediaPipe detects 33 landmarks at 30 FPS<br />
              <span className="text-primary">→ Scoring:</span> Triple-metric comparison every frame<br />
              <span className="text-primary">→ Voice:</span> &quot;Great hip rotation! Extend your kicking leg more — aim for 160°&quot;<br /><br />
              <span className="text-primary">→ Score:</span> <span className="text-green-400">87/100</span> (angles: 82, cosine: 91, OKS: 88)
            </div>
          </div>
        </div>
      </section>

      {/* Model Zoo */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-6xl px-6 py-12">
          <h2 className="text-2xl font-bold mb-6">10 AI Models</h2>
          <div className="flex flex-wrap gap-2">
            {MODELS.map((model) => (
              <Badge key={model} variant="secondary" className="text-sm px-3 py-1.5">
                {model}
              </Badge>
            ))}
          </div>
        </div>
      </section>

      {/* Live Endpoint Test */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-6xl px-6 py-12">
          <h2 className="text-2xl font-bold mb-2">Live Modal A100 Endpoint</h2>
          <p className="text-muted-foreground mb-6">HY-Motion 1.0-Lite generating real 3D motion on NVIDIA A100 GPU.</p>

          <div className="rounded-xl border border-border bg-card p-6">
            <div className="font-mono text-sm mb-4">
              <span className="text-muted-foreground">$</span> curl -X POST{" "}
              <span className="text-primary break-all">
                https://rajashekarvennavelli--aegis-motion-generate-endpoint.modal.run
              </span>
              {" "}\<br />
              &nbsp;&nbsp;-H &quot;Content-Type: application/json&quot; \<br />
              &nbsp;&nbsp;-d {"'{\"prompt\": \"a person doing a squat\", \"num_frames\": 30}'"}<br />
            </div>
            <div className="rounded-lg bg-muted/50 p-4 font-mono text-xs text-muted-foreground">
              <span className="text-green-400">{"{"}</span><br />
              &nbsp;&nbsp;&quot;model&quot;: &quot;HY-Motion 1.0-Lite (Tencent, SOTA Dec 2025)&quot;,<br />
              &nbsp;&nbsp;&quot;device&quot;: &quot;NVIDIA A100 (Modal)&quot;,<br />
              &nbsp;&nbsp;&quot;generation_ms&quot;: 26525.3,<br />
              &nbsp;&nbsp;&quot;num_frames&quot;: 30,<br />
              &nbsp;&nbsp;&quot;raw_shape&quot;: [30, 52, 3],<br />
              &nbsp;&nbsp;&quot;keypoints&quot;: [<span className="text-muted-foreground/50">... 30 frames of MediaPipe 33-point keypoints ...</span>]<br />
              <span className="text-green-400">{"}"}</span>
            </div>
          </div>
        </div>
      </section>

      {/* Technical Paper / Research Section */}
      <section id="research" className="border-b border-border">
        <div className="mx-auto max-w-6xl px-6 py-12">
          <h2 className="text-2xl font-bold mb-2">Technical Paper</h2>
          <p className="text-muted-foreground mb-8">Our approach to AI-driven physical skill coaching.</p>

          <div className="prose prose-invert max-w-none">
            <div className="rounded-xl border border-border bg-card p-8 space-y-6">
              <div className="text-center mb-8">
                <h3 className="text-xl font-bold mb-2">
                  Kinetic: Real-Time AI Skill Coaching Through Expert Motion Transfer and Multi-Modal Feedback
                </h3>
                <p className="text-sm text-muted-foreground">TreeHacks 2026, Stanford University, Stanford, CA</p>
              </div>

              <div>
                <h4 className="font-semibold text-primary mb-2">Abstract</h4>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  We present Kinetic, a real-time AI coaching system that enables users to learn any physical skill
                  without requiring expert video demonstrations. Kinetic introduces a 4-tier expert generation pipeline
                  that synthesizes biomechanically accurate reference poses from natural language descriptions, leveraging
                  canonical biomechanical templates, large language model semantic mapping (Claude Sonnet 4), and
                  state-of-the-art text-to-3D motion generation (HY-Motion 1.0-Lite on NVIDIA A100). Our system
                  evaluates user form using a novel triple-metric scoring engine combining Gaussian joint angle comparison,
                  cosine spatial similarity, and COCO Object Keypoint Similarity (OKS). Real-time feedback is delivered
                  through conversational voice coaching (GPT-4o Realtime API) with 3-layer interruption handling. Edge AI
                  inference on NVIDIA DGX Spark&apos;s GB10 Superchip provides sub-50ms pose estimation latency. The system
                  orchestrates 44 MCP tools across 12 categories through the Anthropic Claude Agent SDK with 3 sub-agents.
                  Kinetic demonstrates that AI-driven coaching can match the quality of human instruction while being
                  accessible to anyone with a camera and microphone.
                </p>
              </div>

              <div>
                <h4 className="font-semibold text-primary mb-2">1. Introduction &amp; Motivation</h4>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Physical skill learning has remained fundamentally unchanged for decades: learners either hire expensive
                  personal coaches ($80–200/hour), follow static video tutorials that cannot observe their form, or use
                  fitness apps that count reps without understanding biomechanics. An estimated 1.7 billion people worldwide
                  desire to learn physical skills — from gym exercises to martial arts to dance — yet lack access to
                  quality, personalized instruction.
                </p>
                <p className="text-sm text-muted-foreground leading-relaxed mt-3">
                  Recent advances in computer vision (MediaPipe, YOLOv8), large language models (Claude, GPT-4o),
                  and motion generation (HY-Motion 1.0) create an unprecedented opportunity to build AI coaching systems
                  that see, understand, and communicate corrections in real-time. However, existing approaches suffer
                  from three key limitations: (1) they require pre-recorded expert demonstrations, limiting skill
                  coverage; (2) they use simplistic single-metric scoring that fails to capture the nuances of
                  human movement; and (3) they lack natural communication interfaces, relying on visual overlays
                  that users cannot observe during active movement.
                </p>
                <p className="text-sm text-muted-foreground leading-relaxed mt-3">
                  Kinetic addresses all three limitations. Our 4-tier expert generation pipeline eliminates the need
                  for demonstration videos. Our triple-metric scoring engine provides robust, multi-dimensional form
                  evaluation. And our voice-first interface delivers corrections naturally during active movement.
                </p>
              </div>

              <div>
                <h4 className="font-semibold text-primary mb-2">2. System Architecture</h4>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Kinetic&apos;s architecture spans 6 infrastructure pillars: (1) NVIDIA DGX Spark for edge AI pose
                  estimation, (2) Modal + NVIDIA A100 for cloud-based motion generation, (3) Anthropic Claude
                  Agent SDK for multi-agent orchestration, (4) OpenAI GPT-4o Realtime API for voice coaching,
                  (5) Google MediaPipe + Ultralytics YOLO for computer vision, and (6) a custom triple-metric
                  scoring engine. Data flows from camera frames through the CV pipeline to the scoring engine,
                  with Claude orchestrating the coaching logic and voice delivering corrections.
                </p>
              </div>

              <div>
                <h4 className="font-semibold text-primary mb-2">3. Triple-Metric Scoring Engine</h4>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Traditional pose scoring relies on a single metric (typically joint angle difference), which fails
                  to capture spatial relationships and overall pose shape. We propose a triple-metric approach:
                </p>
                <ul className="text-sm text-muted-foreground mt-2 space-y-1 list-disc list-inside">
                  <li><strong className="text-foreground">Gaussian Joint Angles (40%)</strong>: Each of 16 key joint angles is scored using a Gaussian function with σ=15°, providing smooth, interpretable per-joint scores.</li>
                  <li><strong className="text-foreground">Cosine Spatial Similarity (30%)</strong>: Normalized skeleton vectors are compared using cosine similarity, capturing overall pose shape independent of body proportions.</li>
                  <li><strong className="text-foreground">COCO OKS (30%)</strong>: Object Keypoint Similarity, the standard metric in academic pose estimation (used in COCO benchmark), provides a weighted evaluation based on joint importance and localization accuracy.</li>
                </ul>
              </div>

              <div>
                <h4 className="font-semibold text-primary mb-2">4. AI Expert Generation Pipeline</h4>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  The key innovation is generating expert references from text alone. Our 4-tier pipeline provides
                  graceful degradation: Tier 1 (canonical templates) serves instant responses for common exercises;
                  Tier 2 (Claude semantic mapping) resolves aliases and variations; Tier 3 (Claude angle generation)
                  handles novel skills through biomechanical reasoning; and Tier 4 (HY-Motion 1.0-Lite on A100)
                  provides state-of-the-art 3D motion diffusion for the most complex cases. Each tier is attempted
                  in order, falling through to the next only when necessary.
                </p>
              </div>

              <div>
                <h4 className="font-semibold text-primary mb-2">5. Edge AI &amp; Latency</h4>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Real-time coaching demands sub-100ms feedback latency. We achieve this through edge AI inference
                  on the NVIDIA DGX Spark&apos;s GB10 Superchip, running YOLOv8n-pose for 17-keypoint estimation
                  at 15+ FPS with &lt;50ms end-to-end latency. This is 4x faster than cloud-based alternatives
                  and enables the tight feedback loop required for movement correction during active exercise.
                </p>
              </div>

              <div>
                <h4 className="font-semibold text-primary mb-2">6. Conclusion</h4>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Kinetic demonstrates that real-time, voice-driven skill coaching is achievable through the
                  combination of edge AI inference, multi-agent LLM orchestration, and state-of-the-art motion
                  generation. By eliminating the requirement for expert video demonstrations, Kinetic makes
                  high-quality physical coaching accessible to anyone with a camera. Future work will explore
                  wearable AR integration, multi-camera 3D reconstruction, and personalized coaching models
                  fine-tuned on individual movement patterns.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Built At */}
      <section className="py-12">
        <div className="mx-auto max-w-6xl px-6 text-center">
          <p className="text-lg font-medium">
            Solo-built in 20 hours. 17,000+ lines. 10 models. 6 infrastructure pillars.
          </p>
          <p className="text-muted-foreground mt-2">
            Built at TreeHacks 2026 🌲 — Stanford University
          </p>
          <div className="mt-6 flex flex-wrap justify-center gap-3">
            {["Anthropic", "OpenAI", "NVIDIA", "Modal", "Tencent", "Google"].map((company) => (
              <Badge key={company} variant="outline" className="text-sm px-3 py-1.5">
                {company}
              </Badge>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
